package app;

public class GameResult {
	//FIELDS
	private final String name;
	private final double win;

	//CONSTRUCTOR
	public GameResult(String name, double win) {
		this.name = name;
		this.win = win;
	}
	
	//GETTER
	String getName() {
		return name;
	}

	double getWin() {
		return win;
	}
	
	//AUTOGENERATED hasCode and equals
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		long temp;
		temp = Double.doubleToLongBits(win);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GameResult other = (GameResult) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (Double.doubleToLongBits(win) != Double.doubleToLongBits(other.win))
			return false;
		return true;
	}
	
}
